package bookingcar.models;
// Generated 2016-11-22 20:51:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * Coach generated by hbm2java
 */
@Entity
@Table(name = "COACH", schema = "dbo", catalog = "Bookingcar")
public class Coach implements java.io.Serializable {

	private int coachid;
	private String coachname;
	private String coachpassword;
	private String coachphone;
	private String coachsex;
	private String coachphotourl;
	private String coachremark;
	private Set<Notice> notices = new HashSet<Notice>(0);
	private Set<Student> students = new HashSet<Student>(0);

	public Coach() {
	}

	public Coach(int coachid) {
		this.coachid = coachid;
	}
	public Coach(String coachphone,String coachpassword) {
		this.coachphone = coachphone;
		this.coachpassword = coachpassword;
	}

	public Coach(int coachid, String coachname, String coachpassword, String coachphone, String coachsex,
			String coachphotourl, String coachremark, Set<Notice> notices, Set<Student> students) {
		this.coachid = coachid;
		this.coachname = coachname;
		this.coachpassword = coachpassword;
		this.coachphone = coachphone;
		this.coachsex = coachsex;
		this.coachphotourl = coachphotourl;
		this.coachremark = coachremark;
		this.notices = notices;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "COACHID", unique = true, nullable = false)
	public int getCoachid() {
		return this.coachid;
	}

	public void setCoachid(int coachid) {
		this.coachid = coachid;
	}

	@Column(name = "COACHNAME")
	public String getCoachname() {
		return this.coachname;
	}

	public void setCoachname(String coachname) {
		this.coachname = coachname;
	}

	@Column(name = "COACHPASSWORD")
	public String getCoachpassword() {
		return this.coachpassword;
	}

	public void setCoachpassword(String coachpassword) {
		this.coachpassword = coachpassword;
	}

	@Column(name = "COACHPHONE",unique = true)
	public String getCoachphone() {
		return this.coachphone;
	}

	public void setCoachphone(String coachphone) {
		this.coachphone = coachphone;
	}

	@Column(name = "COACHSEX")
	public String getCoachsex() {
		return this.coachsex;
	}

	public void setCoachsex(String coachsex) {
		this.coachsex = coachsex;
	}

	@Column(name = "COACHPHOTOURL")
	public String getCoachphotourl() {
		return this.coachphotourl;
	}

	public void setCoachphotourl(String coachphotourl) {
		this.coachphotourl = coachphotourl;
	}

	@Column(name = "COACHREMARK")
	public String getCoachremark() {
		return this.coachremark;
	}

	public void setCoachremark(String coachremark) {
		this.coachremark = coachremark;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "coach")
	public Set<Notice> getNotices() {
		return this.notices;
	}

	public void setNotices(Set<Notice> notices) {
		this.notices = notices;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "coach")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
