package bookingcar.models;
// Generated 2016-11-22 20:51:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name = "NOTICE", schema = "dbo", catalog = "Bookingcar")
public class Notice implements java.io.Serializable {

	private int noticeid;
	private Coach coach;
	private Student student;
	private Date starttime;
	private Date endtime;
	private int readrecord;
	

	public Notice() {
	}

	public Notice(int noticeid) {
		this.noticeid = noticeid;
	}

	public Notice(int noticeid, Coach coach, Student student, Date starttime, Date endtime,int readrecord) {
		this.noticeid = noticeid;
		this.coach = coach;
		this.student = student;
		this.starttime = starttime;
		this.endtime = endtime;
		this.readrecord = readrecord;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "NOTICEID", unique = true, nullable = false)
	public int getNoticeid() {
		return this.noticeid;
	}

	public void setNoticeid(int noticeid) {
		this.noticeid = noticeid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COACH")
	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STUDENT")
	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTTIME", length = 27)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDTIME", length = 27)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}
	
	@Column(name = "READRECORD")
	public int getReadrecord() {
		return readrecord;
	}

	public void setReadrecord(int readrecord) {
		this.readrecord = readrecord;
	}
}
