package bookingcar.models;
// Generated 2016-11-22 20:51:31 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULE", schema = "dbo", catalog = "Bookingcar")
public class Schedule implements java.io.Serializable {

	private int scheduleid;
	private String subjectone;
	private String subjecttwo;
	private String subjectthree;
	private String subjectfour;

	public Schedule() {
	}

	public Schedule(int scheduleid) {
		this.scheduleid = scheduleid;
	}

	public Schedule(int scheduleid, String subjectone, String subjecttwo, String subjectthree, String subjectfour) {
		this.scheduleid = scheduleid;
		this.subjectone = subjectone;
		this.subjecttwo = subjecttwo;
		this.subjectthree = subjectthree;
		this.subjectfour = subjectfour;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "SCHEDULEID", unique = true, nullable = false)
	public int getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(int scheduleid) {
		this.scheduleid = scheduleid;
	}

	@Column(name = "SUBJECTONE")
	public String getSubjectone() {
		return this.subjectone;
	}

	public void setSubjectone(String subjectone) {
		this.subjectone = subjectone;
	}

	@Column(name = "SUBJECTTWO")
	public String getSubjecttwo() {
		return this.subjecttwo;
	}

	public void setSubjecttwo(String subjecttwo) {
		this.subjecttwo = subjecttwo;
	}

	@Column(name = "SUBJECTTHREE")
	public String getSubjectthree() {
		return this.subjectthree;
	}

	public void setSubjectthree(String subjectthree) {
		this.subjectthree = subjectthree;
	}

	@Column(name = "SUBJECTFOUR")
	public String getSubjectfour() {
		return this.subjectfour;
	}

	public void setSubjectfour(String subjectfour) {
		this.subjectfour = subjectfour;
	}

}
