package bookingcar.models;
// Generated 2016-11-22 20:51:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "STUDENT", schema = "dbo", catalog = "Bookingcar")
public class Student implements java.io.Serializable {

	private int studentid;
	private Coach coach;
	private String studentname;
	private String studentphone;
	private String studentpassword;
	private String studentsex;
	private String studentphotourl;
	private String studentremark;
	private Set<Notice> notices = new HashSet<Notice>(0);
	public Student() {
	}

	public Student(int studentid) {
		this.studentid = studentid;
	}

	public Student(int studentid, Coach coach, String studentname, String studentphone, String studentpassword,
			String studentsex, String studentphotourl, String studentremark,Set<Notice> notices) {
		this.studentid = studentid;
		this.coach = coach;
		this.studentname = studentname;
		this.studentphone = studentphone;
		this.studentpassword = studentpassword;
		this.studentsex = studentsex;
		this.studentphotourl = studentphotourl;
		this.studentremark = studentremark;
		this.notices = notices;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "STUDENTID", unique = true, nullable = false)
	public int getStudentid() {
		return this.studentid;
	}

	public void setStudentid(int studentid) {
		this.studentid = studentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COACH")
	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

	@Column(name = "STUDENTNAME")
	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	@Column(name = "STUDENTPHONE",unique = true)
	public String getStudentphone() {
		return this.studentphone;
	}

	public void setStudentphone(String studentphone) {
		this.studentphone = studentphone;
	}

	@Column(name = "STUDENTPASSWORD")
	public String getStudentpassword() {
		return this.studentpassword;
	}

	public void setStudentpassword(String studentpassword) {
		this.studentpassword = studentpassword;
	}

	@Column(name = "STUDENTSEX")
	public String getStudentsex() {
		return this.studentsex;
	}

	public void setStudentsex(String studentsex) {
		this.studentsex = studentsex;
	}

	@Column(name = "STUDENTPHOTOURL")
	public String getStudentphotourl() {
		return this.studentphotourl;
	}

	public void setStudentphotourl(String studentphotourl) {
		this.studentphotourl = studentphotourl;
	}

	@Column(name = "STUDENTREMARK")
	public String getStudentremark() {
		return this.studentremark;
	}

	public void setStudentremark(String studentremark) {
		this.studentremark = studentremark;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "student")
	public Set<Notice> getNotices() {
		return this.notices;
	}

	public void setNotices(Set<Notice> notices) {
		this.notices = notices;
	}
}
